Feature/ioiob 27
Iorweth333/Scheduling_supporter pull request #14
Opened 2019-05-13 17:23 UTC by Malenczuk

2019-05-15 16:15 UTC, kzycinski reviewed
Małe błędy do poprawy i można mergować, trzeba jeszcze dopisać nowe endpointy do readme

2019-05-15 16:15 UTC, legendar1o commented on backend/src/main/java/ioiobagiety/service/AppUserService.java
> +    AppUser create (AppUser user) throws BadRequestException;
Czemu create rzuca inny exception?

2019-05-15 16:15 UTC, legendar1o commented on backend/src/main/java/ioiobagiety/service/EmailService.java
> +public interface EmailService {
Czemu 2 metody robiące w zasadzie to samo mają różne exceptiony?

2019-05-15 16:15 UTC, legendar1o commented on backend/src/main/java/ioiobagiety/service/impl/BasicEmailReminderService.java
> +            text.append("Subject: ").append(lesson.getSubject().getName())
Wygląda to średnio i mało czytelnie, lepszą wersją byłoby np.:
appendSubject(text);
i analogicznie dla reszty

2019-05-16 11:42 UTC, Iorweth333 requested changes
Zwracam uwagę na gettery w klasach modelu i liczne nieużywane importy

2019-05-16 11:42 UTC, Iorweth333 commented on backend/src/main/java/ioiobagiety/repository/AppUserRepository.java
> +import ioiobagiety.model.classes.Lesson;
nieużywany import

2019-05-16 11:42 UTC, Iorweth333 commented on backend/src/main/java/ioiobagiety/repository/AppUserRepository.java
> +import java.util.List;
jeszcze jeden nieużywany import

2019-05-16 11:42 UTC, Iorweth333 commented on backend/src/main/java/ioiobagiety/service/AppUserService.java
> +import ioiobagiety.model.classes.Lesson;
nieużywany import

2019-05-16 11:42 UTC, Iorweth333 commented on backend/src/main/java/ioiobagiety/service/impl/BasicAppUserService.java
> +import ioiobagiety.model.classes.Lesson;
trzy nieużywane importy

2019-05-16 11:42 UTC, Iorweth333 commented on backend/src/main/java/ioiobagiety/service/impl/BasicEmailReminderService.java
> +            emailService.sendSimpleMessage(user.getEmail(), "Lesson Reminder", msg);
czy tylko mi tutaj świeci na czerwono?
w klasach AppUser i Lesson brakuje getterów, które są tu w całej klasie używane
co ciekawe: Travis świeci na zielono. sprawdziłem więc lokalnie i wszystkie komendy: gradlew assemble, gradlew check i gradle build skończyły się sukcesem
I humbly ask myself: dafuq?

2019-05-16 11:44 UTC, legendar1o commented on backend/src/main/java/ioiobagiety/service/impl/BasicEmailReminderService.java
> +            emailService.sendSimpleMessage(user.getEmail(), "Lesson Reminder", msg);
Potrzebujesz pluginu do lomboka i włączyć ustawienia, żeby kompilator sprawdzał adnotacje

> 
> 
> czy tylko mi tutaj świeci na czerwono?
> w klasach AppUser i Lesson brakuje getterów, które są tu w całej klasie używane
> co ciekawe: Travis świeci na zielono. sprawdziłem więc lokalnie i wszystkie komendy: gradlew assemble, gradlew check i gradle build skończyły się sukcesem
> I humbly ask myself: dafuq?

2019-05-22 16:39 UTC, kzycinski reviewed
ok

2019-05-22 16:41 UTC, merged