Feature/ioiob 100
Iorweth333/Scheduling_supporter pull request #23
Opened 2019-06-11 19:43 UTC by Atzon

2019-06-11 21:50 UTC, pbartkowicz requested changes

2019-06-11 21:50 UTC, pbartkowicz commented on backend/src/main/java/ioiobagiety/service/LessonService.java
Tutaj jest chyba pozostałość z diffa innego merg'a, tak samo poniżej

2019-06-12 12:06 UTC, Atzon reviewed
Ok

2019-06-12 15:00 UTC, pbartkowicz approved these changes

2019-06-12 15:02 UTC, merged